title: Mason D Young
email: msnyng@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I Love learning!
baseurl: ""
url: "https://msnyng.com"
twitter_username: masonyoung
github_username:  qst0

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
